name = "non_empty_list"
version = "1.1.0"
description = "Non-empty lists in Gleam"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "non_empty_list" }
links = []

[dependencies]
gleam_stdlib = "~> 0.30"

[dev-dependencies]
gleeunit = "~> 0.10"
