name = "non_empty_list"
version = "0.1.0"
description = "A Gleam project"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "non_empty_list" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.29"

[dev-dependencies]
glacier = "~> 0.8"
